### ISSUE TITLE
源站的ssl证书过期或者错误的情况下无法使用？

### ISSUE THREAD

**Issue by boscat** [hax0r31337/EgressGuy#2]
有办法解决嘛？显示以下错误 
probing for redirects...2024/09/10 11:05:35 failed to probe for redirects: Get "https://源站地址": tls: failed to verify certificate: x509: certificate is valid for xx域名, not  xx域名
或者怎么跳过ssl证书错误？

**Comment by hax0r31337** [comment]
https://github.com/hax0r31337/EgressGuy/blob/c45034aa2505cb37b144668c20173a23d9cb0c7f/main/main.go#L126

Add code here to declare skip certificate verification
```go
InsecureSkipVerify: true,
```

**Comment by hax0r31337** [comment]
closed due to timed out
